feedback_form/urls.py
from django.urls import path
from django.conf import settings
from . import views
from django.conf.urls.static import static

app_name = 'feedback'
urlpatterns = [
    path('',views.index,name='index'),
        #Login
        path('loginview', views.loginview, name='loginview'),
        path('login/process', views.process, name='process'),
        path('logout', views.processlogout, name='processlogout'),

        #Account
        path('home', views.home, name='home'),
        path('adminhome',views.adminhome, name="adminhome"),
        path('accountsearch', views.accountsearch, name='accountsearch'),
        path('adminaddacc', views.adminAddAcc, name="adminaddacc"),
        path('adminaddacc/add_acc', views.add_acc, name="add_acc") ,
        # path('<int:user_id>/delete_acc/', views.delete_acc, name='delete_acc'),
        path('<int:user_id>/deactivate_acc/', views.deactivate_acc, name='deactivate_acc'),
        path('<int:user_id>/activate_acc/', views.activate_acc, name='activate_acc'),
        path('<int:user_id>/edit_acc/', views.edit_acc, name='edit_acc'),
        path('<int:user_id>/process_acc_edit/', views.process_acc_edit, name='process_acc_edit'),

        #User Settings
        path('usersettings', views.usersettings, name="usersettings"),
        path('editusersettings', views.editusersettings, name="editusersettings"),
        path('<int:user_id>/updateusersettings/',views.updateusersettings, name="updateusersettings"),

        #Employee
        path('employeelist', views.employeelist, name="employeelist"),
        path('employeesearch', views.employeesearch, name='employeesearch'),
        path('addemployee', views.addemployee, name='addemployee'),
        path('processaddemployee', views.processaddemployee, name='processaddemployee'),
        path('<int:employee_id>/deactivate_employee/',views.deactivate_employee,name="deactivate_employee"),
        path('<int:employee_id>/activate_employee/',views.activate_employee,name="activate_employee"),
        # path('<int:employee_id>/delete_employee/',views.delete_employee,name="delete_employee"),
        path('<int:employee_id>/edit_employee/',views.edit_employee,name="edit_employee"),
        path('<int:employee_id>/process_edit_employee/', views.process_edit_employee, name='process_edit_employee'),

        #Feedback
        path('generate_feedbackhome', views.generate_feedbackhome, name="generate_feedbackhome"),
        path('generate_client',views.generate_client,name="generate_client"),
        path('client_process', views.client_process, name="client_process"),
        path('client_feedback/<str:token>/<str:encrypt>/', views.client_feedback, name='client_feedback'),
        path('process_feedback',views.process_feedback, name="process_feedback"),
        path('thankyou', views.thankyou, name="thankyou"),

        #reports
        path('reportshome',views.reportshome, name='reportshome'),
        path('report_offices', views.report_offices, name='report_offices'),
        path('report_offices_search', views.report_offices_search, name='report_offices_search'),
        path('<int:user_id>/reports_feedbacks_search',views.reports_feedbacks_search,name='reports_feedbacks_search'),
        path('<int:user_id>/reports_officesummary',views.reports_officesummary,name='reports_officesummary'),
        path('<int:user_id>/reports_feedbacks',views.reports_feedbacks,name='reports_feedbacks'),
        path('<int:user_id>/reports_viewreports',views.reports_viewreports,name='reports_viewreports'),
        path('<int:user_id>/reports_viewreports_search',views.reports_viewreports_search,name='reports_viewreports_search'),
        path('<int:user_id>/reports_staff',views.reports_staff,name='reports_staff'),
        path('<int:user_id>/reports_staff_search',views.reports_staff_search,name='reports_staff_search'),
        path('<int:user_id>/<int:client_id>/reports_single',views.reports_single, name='reports_single'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sentiment_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('feedback_form.urls')),
]

templates/reports/reports_feedbacks.html
{% extends 'SideBar.html' %}
{% load static %}
{% load tz %}

{% block pagecss %}
<link rel="stylesheet" href="{% static 'css/reports/reports_feedbacks.css' %}">
{% endblock%}

{% block title %}
Reports
{% endblock %}

{% block content %}
    <div class='reportlist_page'>
        <h1>REPORT LIST</h1>
        <div class='Search_bar'>
            <form action="{% url 'feedback:reports_feedbacks_search' office.id %}" method="GET" id="search-form">
                <input type="text" placeholder="Search Client" name="search" id="search-input" />
                <select name="category" id="search-category" class="filter">
                    <option value="">Polarity</option>
                    <option value="positive">Positive</option>
                    <option value="neutral">Neutral</option>
                    <option value="negative">Negative</option>
                </select>
                <label>From:</label>
                <input type="date" name="date_from" id="date-from" placeholder="Date From" class="filter"/>
                <label>To:</label>
                <input type="date" name="date_to" id="date-to" placeholder="Date To" class="filter"/>
            </form>
        </div>
        <div class="client_tbl">
            <table id="search-results">
                <tr>
                    <th>Name</th>
                    <th>Date</th>
                    <th>Average</th>
                    <th>Sentiment Analysis</th>
                    <th>Feedback </th>
                </tr>
                {% for client in clients %}
                <tr key={key}>
                    <td>{{client.client_name}}</td>
                    <td>{{client.client_visit_date|timezone:"Asia/Manila"|date:"F j, Y g:i A" }}</td>
                    <td>{{client.rating}}</td>
                    {% if client.sentiment == "positive" %}
                        <td>
                            <span class="sentiment-value">{{ client.sentiment }}</span>
                        </td>
                    {% elif client.sentiment == "neutral" %}
                        <td>
                            <span class="sentiment-value">{{ client.sentiment }}</span>
                        </td>
                    {% else %}
                        <td>
                            <span class="sentiment-value">{{ client.sentiment }}</span>
                        </td>
                    {% endif %}
                    <td class="vw"><a href="{% url 'feedback:reports_single' office.id client.id %}">view</a></td>
                 </tr>
                 {% endfor %}
            </table>
            <div class="pagebutton">
                <ul class="pagination">
                    {% if clients.has_previous %}
                        <li class="page-item"><a href="?page=1" class="page-link">&laquo; First </a></li>
                        <li class="page-item"><a href="?page={{ clients.previous_page_number }}" class="page-link"> Previous </a></li>
                    {% endif %}
        
                    {% if clients.has_next %}
                        <li class="page-item"><a href="?page={{ clients.next_page_number }}" class="page-link"> Next </a></li>
                        <li class="page-item"><a href="?page={{ clients.paginator.num_pages }}" class="page-link">&raquo; Last </a></li>
                    {% endif %}
                </ul>  
            </div>

        </div>
    </div>

    <script>
$(document).ready(function() {
    var searchTimeout;

    $('#search-input, #search-category').on('input', function() {
        clearTimeout(searchTimeout);
        searchTimeout = setTimeout(getSearchResults, 300); // Delay the search by 300 milliseconds
    });

    $('#date-from, #date-to').on('change', function() {
        getSearchResults();
    });

    function getSearchResults() {
        var searchValue = $('#search-input').val();
        var categoryValue = $('#search-category').val();
        var dateFromValue = $('#date-from').val();
        var dateToValue = $('#date-to').val();

        // Adding one day to the date_to value
        if (dateToValue) {
            var dateTo = new Date(dateToValue);
            dateTo.setDate(dateTo.getDate() + 1);
            dateToValue = dateTo.toISOString().split('T')[0];
        }

        $.ajax({
            url: $('#search-form').attr('action'),
            method: 'GET',
            data: {
                search: searchValue,
                category: categoryValue,
                date_from: dateFromValue,
                date_to: dateToValue
            },
            success: function(response) {
                var searchResultsHTML = $(response).find('.client_tbl').html();
                $('#search-results').html(searchResultsHTML);
            },
            error: function(xhr, textStatus, error) {
                console.log(error);
            }
        });
    }
});
    </script>
{% endblock %}

templates/reports/reports_offices.html
{% extends 'SideBar.html' %}
{% load static %}

{% block pagecss %}
<link rel="stylesheet" href="{% static 'css/reports/reports_offices.css' %}">
{% endblock%}

{% block title %}
Reports
{% endblock %}

{% block content %}
    <div class='reportlist_page'>
        <h1>REPORT LIST</h1>
        <div class='Search_bar'>
            <form action="{% url 'feedback:report_offices_search' %}" method="GET" id="search-form">
                <input type="text" placeholder="Search Account" name="search" id="search-input" />
                <select name="category" id="search-category" class="filter">
                    <option value="">Active Status</option>
                    <option value="True">Active</option>
                    <option value="False">Inactive</option>
                </select>
            </form>
        </div>
        <div class="client_tbl" id="search-results" >
            <table >
                <tr>
                    <th>OFFICE</th>
                    <th>LAST LOGIN</th>
                    <th>STATUS</th>
                    <th>ACTION</th>
                </tr>
                {% for user in users %}
                <tr key={key}>
                    <td>{{user.first_name}}</td>
                    <td>{{user.last_login}}</td>
                    {% if user.is_active %}
                        <td id="active">Active</td>
                    {% else %}
                        <td id="inactive">Inactive</td>
                    {% endif %}
                    <td class="vw"><a href="{% url 'feedback:reports_officesummary' user.id%}">view</a></td>
                </tr>
                {% endfor %}
            </table>
            <div class="pagebutton">
                <ul class="pagination">
                    {% if users.has_previous %}
                        <li class="page-item"><a href="?page=1" class="page-link">&laquo; First </a></li>
                        <li class="page-item"><a href="?page={{ users.previous_page_number }}" class="page-link"> Previous </a></li>
                    {% endif %}
        
                    {% if users.has_next %}
                        <li class="page-item"><a href="?page={{ users.next_page_number }}" class="page-link"> Next </a></li>
                        <li class="page-item"><a href="?page={{ users.paginator.num_pages }}" class="page-link">&raquo; Last </a></li>
        
                    {% endif %}
                </ul>  
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function() {
            var searchTimeout;
    
            $('#search-input, #search-category').on('input', function() {
                clearTimeout(searchTimeout);
                searchTimeout = setTimeout(getSearchResults, 300); // Delay the search by 300 milliseconds
            });
    
            function getSearchResults() {
                var searchValue = $('#search-input').val();
                var categoryValue = $('#search-category').val();
                $.ajax({
                    url: $('#search-form').attr('action'),
                    method: 'GET',
                    data: { search: searchValue, category: categoryValue },
                    success: function(response) {
                        var searchResultsHTML = $(response).find('.client_tbl').html();
                        $('#search-results').html(searchResultsHTML);
                    },
                    error: function(xhr, textStatus, error) {
                        console.log(error);
                    }
                });
            }
        });
    </script>
    
{% endblock %}

templates/reports/reports_officesummary.html
{% extends 'SideBar.html' %}
{% load static %}

{% block pagecss %}
<link rel="stylesheet" href="{% static 'css/reports/reports_officesummary.css' %}">
{% endblock%}

{% block title %}
Reports
{% endblock %}

{% block content %}
<div class='reports_page'>
    <Header></Header>
    <h1 class="headtitle"> FEEDBACK REPORTS </h1>
    <div class="office_name">
        <h3>Office:</h3>
        <p>{{office.first_name}} OFFICE</p>
    </div>
    <!-- <div class='tbl_graph'>
         PIE CHART 
        <h2> Sentiment Analysis Report</h2>
    </div> -->
    <table class="report_data">
        <tr>
            <td>
                <div class="clnts">
                    <p>CLIENTS</p>
                    <h3>{{client_count}}</h3>
                    <h3>RESPONDENTS</h3>
                </div>
            </td>

            <td>
                <div class="oar">
                    <p>OVERALL AVG. RATING</p>
                    <h3>{{feedback_average}}</h3>
                    <h3>AVERAGE</h3>
                </div>
            </td>
        </tr>
    </table>
    <table class="view_reportdata">
        <tr>
            <td class='viewsr'>
                <a href="{% url 'feedback:reports_feedbacks' office.id%}"><button type="button" class='vlfr'>View All Feedback Reports</button></a>
            </td>

            <td class='viewsr'>
                <a href="{% url 'feedback:reports_viewreports' office.id%}"><button type="button" class='vsr'>View Summary Report</button></a>
            </td>
            <td class='viewsr'>
                <a href="{% url 'feedback:reports_staff' office.id%}"><button type="button" class='ver'>View Employee Rating</button></a>
            </td>
        </tr>
    </table>
    <ReportList></ReportList>
</div>
{% endblock %}

templates/reports/reports_single.html
{% extends 'feedbackbase.html' %}
{% load static %}
{% load tz %}

{% block pagecss %}
<link rel="stylesheet" href="{% static 'css/reports/reports_single.css' %}">
{% endblock%}

{% block title %}
Reports
{% endblock %}

{% block content %}
<h4>Client Name: <span>{{client.client_name}}</span></h4> 
<h4>Date: <span>{{ client.client_visit_date|timezone:"Asia/Manila"|date:"F j, Y H:i A" }}</span></h4>
<h4>Feedback Polarity: <span>{{sentiment.sentiment_analysis}}</span></h4>
<div class="main">
    <div class="Container">
        <p id="SFF">STAKEHOLDERS' FEEDBACK FORM</p>
            <table>
                <tr class="heads">
                    <th>Area of Concern</th>
                    <td>Highly</td>
                    <td>Very Satisfied</td>
                    <td>Moderately Satisfied</td>
                    <td>Barely Satisfied</td>
                    <td>Not Satisfied</td>
                    <td>Average Rating</td>
                </tr>
                <tr>
                    <th></th>
                    <td>5</td>
                    <td>4</td>
                    <td>3</td>
                    <td>2</td>
                    <td>1</td>
                </tr>
                <tr>
                    <th>A . Courtesy</th>
                    <td>{% if feedback.feedback_courtesy == 5%}✓{% endif %}</td>
                <td>{% if feedback.feedback_courtesy == 4%}✓{% endif %}</td>
                <td>{% if feedback.feedback_courtesy == 3%}✓{% endif %}</td>
                <td>{% if feedback.feedback_courtesy == 2%}✓{% endif %}</td>
                <td>{% if feedback.feedback_courtesy == 1%}✓{% endif %}</td>
                <td>{{feedback.feedback_courtesy}}</td>
                </tr>
                <tr>
                    <th>B . Services</th>
                </tr>
                <tr>
                    <th id="satisfactory">1 . Quality</th>
                    <td>{% if feedback.feedback_quality == 5%}✓{% endif %}</td>
                <td>{% if feedback.feedback_quality == 4%}✓{% endif %}</td>
                <td>{% if feedback.feedback_quality == 3%}✓{% endif %}</td>
                <td>{% if feedback.feedback_quality == 2%}✓{% endif %}</td>
                <td>{% if feedback.feedback_quality == 1%}✓{% endif %}</td>
                <td>{{feedback.feedback_quality}}</td>
                </tr>
                <tr>
                    <th id="satisfactory">2 . Timeliness</th>
                    <td>{% if feedback.feedback_timeless == 5%}✓{% endif %}</td>
                <td>{% if feedback.feedback_timeless == 4%}✓{% endif %}</td>
                <td>{% if feedback.feedback_timeless == 3%}✓{% endif %}</td>
                <td>{% if feedback.feedback_timeless == 2%}✓{% endif %}</td>
                <td>{% if feedback.feedback_timeless == 1%}✓{% endif %}</td>
                <td>{{feedback.feedback_timeless}}</td>
                </tr>
                <tr>
                    <th id="satisfactory">3 . Efficiency</th>
                    <td>{% if feedback.feedback_efficiency == 5%}✓{% endif %}</td>
                <td>{% if feedback.feedback_efficiency == 4%}✓{% endif %}</td>
                <td>{% if feedback.feedback_efficiency == 3%}✓{% endif %}</td>
                <td>{% if feedback.feedback_efficiency == 2%}✓{% endif %}</td>
                <td>{% if feedback.feedback_efficiency == 1%}✓{% endif %}</td>
                <td>{{feedback.feedback_efficiency}}</td>
                </tr>
                <tr>
                    <th>C .  Physical Condition of workspace</th>
                </tr>
                <tr>
                    <th id="satisfactory">1 . Cleanliness</th>
                    <td>{% if feedback.feedback_cleanliness == 5%}✓{% endif %}</td>
                <td>{% if feedback.feedback_cleanliness == 4%}✓{% endif %}</td>
                <td>{% if feedback.feedback_cleanliness == 3%}✓{% endif %}</td>
                <td>{% if feedback.feedback_cleanliness == 2%}✓{% endif %}</td>
                <td>{% if feedback.feedback_cleanliness == 1%}✓{% endif %}</td>
                <td>{{feedback.feedback_efficiency}}</td>
                </tr>
                <tr>
                    <th id="satisfactory">2 . Comfort</th>
                    <td>{% if feedback.feedback_comfort == 5%}✓{% endif %}</td>
                <td>{% if feedback.feedback_comfort == 4%}✓{% endif %}</td>
                <td>{% if feedback.feedback_comfort == 3%}✓{% endif %}</td>
                <td>{% if feedback.feedback_comfort == 2%}✓{% endif %}</td>
                <td>{% if feedback.feedback_comfort == 1%}✓{% endif %}</td>
                <td>{{feedback.feedback_comfort}}</td>
                </tr>
                <tr>
                    <th></th>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td id="quarterly-report">Overall Average Rating</td>
                    <td class="rating">{{rating}}</td>
                </tr>
            </table>
            <label>Comments and Suggestion:</label>
            <textarea disabled="yes" name="comments" placeholder= "{{feedback.feedback_comments}}"></textarea>
            <div class="fback">
                <!-- <div class="outcome">
                    {% if sentiment.sentiment_analysis == 'positive' %}
                    <img src="{% static 'image/reports/smiley.png' %}">
                    {% elif sentiment.sentiment_analysis == 'negative' %}
                    <img src="{% static 'image/reports/sad.png' %}">
                    {% else %}
                    <img src="{% static 'image/reports/neutral.png' %}">
                    {% endif %}
                </div> -->
            </div>
            <div class='back'>
                <a href="{% url 'feedback:reports_feedbacks' office.id%}"><button type="button" class='back_button'>Back</button></a>
            </div>
    </div>
</div>
{% endblock %}

templates/reports/reports_staff.html
{% extends 'feedbackbase.html' %}
{% load static %}

{% block pagecss %}
<link rel="stylesheet" href="{% static 'css/reports/reports_staff.css' %}">
{% endblock%}

{% block title %}
Reports
{% endblock %}

{% block content %}
    <div>
        <h1> EMPLOYEE REPORTS </h1>
        <h4>OFFICE: <span>{{ office.first_name }}</span></h4> 
    </div>
    <div class="Search_bar">
        <form action="{% url 'feedback:reports_staff_search' office.id %}" method="GET" id="search-form">
            <label>From:</label>
        <input type="date" name="date_from" id="date-from" placeholder="Date From" class="filter"/>
        <label>To:</label>
        <input type="date" name="date_to" id="date-to" placeholder="Date To" class="filter"/>
        <input type="submit" id="filter-button" value="Filter Date"/>
        </form>
    </div>
    <div class="main">
        <div class="container">
            <p id="SFF">STAKEHOLDERS' FEEDBACK FORM EMPLOYEE REPORT</p>
            <p>Courtesy and Service of Staff</p>
            <table>
                <tr>
                    <th>Name of Staff</th>
                    <th>No. of Clients</th>
                    <th>Overall Rating</th>
                    <th>Employee Status</th>
                    <th>Remarks</th>
                    <th>Action/s Taken</th>
                </tr>
                {% for employee in employees %}
                <tr>
                    <td>{{ employee.first_name }} {{ employee.last_name }}</td>
                    <td>{{ employee.client_count }}</td>
                    <td class="rating">
                        {% if employee.feedback_average %}
                            {{ employee.feedback_average }}
                        {% else %}
                            0.00
                        {% endif %}
                    </td>
                    {% if employee.is_active %}
                        <td>Active</td>
                    {% else %}
                        <td>Inactive</td>
                    {% endif %}
                    <td></td>
                    <td></td>
                </tr>
                {% endfor %}
            </table>
    
            <div class='back'>
                <a href="{% url 'feedback:reports_officesummary' office.id %}"><button type="button" class='back_button'>Back</button></a>
            </div>
        </div>
    </div>
{% endblock %}

templates/reports/reports_viewreports.html
{% extends 'feedbackbase.html' %}
{% load static %}

{% block pagecss %}
<link rel="stylesheet" href="{% static 'css/reports/reports_viewreports.css' %}">
{% endblock%}

{% block title %}
Reports
{% endblock %}

{% block content %}
<h1> OVERALL REPORT </h1>
<h4>OFFICE: <span>{{office.first_name}}</span></h4> 
<div class="Search_bar">
    <form action="{% url 'feedback:reports_viewreports_search' user.id %}" method="GET" id="search-form">
        <label>From:</label>
        <input type="date" name="date_from" id="date-from" placeholder="Date From" class="filter"/>
        <label>To:</label>
        <input type="date" name="date_to" id="date-to" placeholder="Date To" class="filter"/>
        <input type="submit" id="filter-button" value="Filter Date"/>
    </form>
</div>
<div class="main">
    <div class="Container">
        <p id="SFF">STAKEHOLDERS' FEEDBACK FORM</p>
            <table>
                <tr class="heads">
                    <th>Area of Concern</th>
                    <td>Highly</td>
                    <td>Very Satisfied</td>
                    <td>Moderately Satisfied</td>
                    <td>Barely Satisfied</td>
                    <td>Not Satisfied</td>
                    <td>Average Rating</td>
                </tr>
                <tr>
                    <th></th>
                    <td>5</td>
                    <td>4</td>
                    <td>3</td>
                    <td>2</td>
                    <td>1</td>
                </tr>
                <tr>
                    <th>A . Courtesy</th>
                    <td>{{ courtesy_counts.5|default_if_none:'' }}</td>
                    <td>{{ courtesy_counts.4|default_if_none:'' }}</td>
                    <td>{{ courtesy_counts.3|default_if_none:'' }}</td>
                    <td>{{ courtesy_counts.2|default_if_none:'' }}</td>
                    <td>{{ courtesy_counts.1|default_if_none:'' }}</td>
                    <td class="rating">{{ courtesy_rating }}</td>
                </tr>
                <tr>
                    <th>B . Services</th>
                </tr>
                <tr>
                    <th id="satisfactory">1 . Quality</th>
                    <td>{{ quality_counts.5|default_if_none:'' }}</td>
                    <td>{{ quality_counts.4|default_if_none:'' }}</td>
                    <td>{{ quality_counts.3|default_if_none:'' }}</td>
                    <td>{{ quality_counts.2|default_if_none:'' }}</td>
                    <td>{{ quality_counts.1|default_if_none:'' }}</td>
                    <td class="rating">{{ quality_rating }} </td>
                </tr>
                <tr>
                    <th id="satisfactory">2 . Timeliness</th>
                    <td>{{ timeless_counts.5|default_if_none:'' }}</td>
                    <td>{{ timeless_counts.4|default_if_none:'' }}</td>
                    <td>{{ timeless_counts.3|default_if_none:'' }}</td>
                    <td>{{ timeless_counts.2|default_if_none:'' }}</td>
                    <td>{{ timeless_counts.1|default_if_none:'' }}</td>
                    <td class="rating">{{ timeless_rating }} </td>
                </tr>
                <tr>
                    <th id="satisfactory">3 . Efficiency</th>
                    <td>{{ efficiency_counts.5|default_if_none:'' }}</td>
                    <td>{{ efficiency_counts.4|default_if_none:'' }}</td>
                    <td>{{ efficiency_counts.3|default_if_none:'' }}</td>
                    <td>{{ efficiency_counts.2|default_if_none:'' }}</td>
                    <td>{{ efficiency_counts.1|default_if_none:'' }}</td>
                    <td class="rating">{{ efficiency_rating }} </td>
                </tr>
                <tr>
                    <th>C .  Physical Condition of workspace</th>
                </tr>
                <tr>
                    <th id="satisfactory">1 . Cleanliness</th>
                    <td>{{ cleanliness_counts.5|default_if_none:'' }}</td>
                    <td>{{ cleanliness_counts.4|default_if_none:'' }}</td>
                    <td>{{ cleanliness_counts.3|default_if_none:'' }}</td>
                    <td>{{ cleanliness_counts.2|default_if_none:'' }}</td>
                    <td>{{ cleanliness_counts.1|default_if_none:'' }}</td>
                    <td class="rating">{{ cleanliness_rating }} </td>
                </tr>
                <tr>
                    <th id="satisfactory">2 . Comfort</th>
                    <td>{{ comfort_counts.5|default_if_none:'' }}</td>
                    <td>{{ comfort_counts.4|default_if_none:'' }}</td>
                    <td>{{ comfort_counts.3|default_if_none:'' }}</td>
                    <td>{{ comfort_counts.2|default_if_none:'' }}</td>
                    <td>{{ comfort_counts.1|default_if_none:'' }}</td>
                    <td class="rating">{{ comfort_rating }} </td>
                </tr>
                <tr>
                    <th></th>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td id="quarterly-report">Overall Average Rating</td>
                    <td class="rating">{{feedback_average}}</td>
                </tr>
            </table>
            <div class='back'>
                <a href="{% url 'feedback:reports_officesummary' office.id%}"><button type="button" class='back_button'>Back</button></a>
            </div>
    </div>
</div>
</div>
{% endblock %}

templates/reports/reportshome.html
{% extends 'SideBar.html' %}
{% load static %}

{% block pagecss %}
<link rel="stylesheet" href="{% static 'css/reports/reportshome.css' %}">
{% endblock%}

{% block title %}
Reports
{% endblock %}

{% block content %}
<div class='reports_page'>
    <Header></Header>
    <h1 class="headtitle"> REPORTS </h1>
    <table class="report_data">
        <tr>
            {% if user.userclass.status == 1%}
            <td>
                <div class="tsr">
                    <p>NUMBER OF ACTIVE OFFICES</p>
                    <h3>{{obj.user_count}}</h3>
                    <h3>OFFICE</h3>
                </div>
            </td>
            {% endif %}
            <td>
                <div class="tc">
                    <p>TOTAL CLIENTS </p>
                    <h3>{{obj.client_count}}</h3>
                    <h3>RESPONDENTS</h3>
                </div>
            </td>

            <td>
                <div class="oar">
                    <p>OVERALL AVG. RATING</p>
                    <h3>{{obj.feedback_average}}</h3>
                    <h3>AVERAGE</h3>
                </div>
            </td>
        </tr>

    </table>

    <div class='listoffice'>
        {% if user.userclass.status == 1%}
            <a href="{% url 'feedback:report_offices' %}"><button type="button" class='lor'>List of Office Reports</button></a>
        {% else %}
            <a href="{% url 'feedback:reports_officesummary' user.id %}"><button type="button" class='lor'>Office Report</button></a>
        {% endif %}
    </div>
    <ReportList></ReportList>

</div>
{% endblock %}