feedback_form/urls.py
from django.urls import path
from django.conf import settings
from . import views
from django.conf.urls.static import static

app_name = 'feedback'
urlpatterns = [
    path('',views.index,name='index'),
        #Login
        path('loginview', views.loginview, name='loginview'),
        path('login/process', views.process, name='process'),
        path('logout', views.processlogout, name='processlogout'),

        #Account
        path('home', views.home, name='home'),
        path('adminhome',views.adminhome, name="adminhome"),
        path('accountsearch', views.accountsearch, name='accountsearch'),
        path('adminaddacc', views.adminAddAcc, name="adminaddacc"),
        path('adminaddacc/add_acc', views.add_acc, name="add_acc") ,
        # path('<int:user_id>/delete_acc/', views.delete_acc, name='delete_acc'),
        path('<int:user_id>/deactivate_acc/', views.deactivate_acc, name='deactivate_acc'),
        path('<int:user_id>/activate_acc/', views.activate_acc, name='activate_acc'),
        path('<int:user_id>/edit_acc/', views.edit_acc, name='edit_acc'),
        path('<int:user_id>/process_acc_edit/', views.process_acc_edit, name='process_acc_edit'),

        #User Settings
        path('usersettings', views.usersettings, name="usersettings"),
        path('editusersettings', views.editusersettings, name="editusersettings"),
        path('<int:user_id>/updateusersettings/',views.updateusersettings, name="updateusersettings"),

        #Employee
        path('employeelist', views.employeelist, name="employeelist"),
        path('employeesearch', views.employeesearch, name='employeesearch'),
        path('addemployee', views.addemployee, name='addemployee'),
        path('processaddemployee', views.processaddemployee, name='processaddemployee'),
        path('<int:employee_id>/deactivate_employee/',views.deactivate_employee,name="deactivate_employee"),
        path('<int:employee_id>/activate_employee/',views.activate_employee,name="activate_employee"),
        # path('<int:employee_id>/delete_employee/',views.delete_employee,name="delete_employee"),
        path('<int:employee_id>/edit_employee/',views.edit_employee,name="edit_employee"),
        path('<int:employee_id>/process_edit_employee/', views.process_edit_employee, name='process_edit_employee'),

        #Feedback
        path('generate_feedbackhome', views.generate_feedbackhome, name="generate_feedbackhome"),
        path('generate_client',views.generate_client,name="generate_client"),
        path('client_process', views.client_process, name="client_process"),
        path('client_feedback/<str:token>/<str:encrypt>/', views.client_feedback, name='client_feedback'),
        path('process_feedback',views.process_feedback, name="process_feedback"),
        path('thankyou', views.thankyou, name="thankyou"),

        #reports
        path('reportshome',views.reportshome, name='reportshome'),
        path('report_offices', views.report_offices, name='report_offices'),
        path('report_offices_search', views.report_offices_search, name='report_offices_search'),
        path('<int:user_id>/reports_feedbacks_search',views.reports_feedbacks_search,name='reports_feedbacks_search'),
        path('<int:user_id>/reports_officesummary',views.reports_officesummary,name='reports_officesummary'),
        path('<int:user_id>/reports_feedbacks',views.reports_feedbacks,name='reports_feedbacks'),
        path('<int:user_id>/reports_viewreports',views.reports_viewreports,name='reports_viewreports'),
        path('<int:user_id>/reports_viewreports_search',views.reports_viewreports_search,name='reports_viewreports_search'),
        path('<int:user_id>/reports_staff',views.reports_staff,name='reports_staff'),
        path('<int:user_id>/reports_staff_search',views.reports_staff_search,name='reports_staff_search'),
        path('<int:user_id>/<int:client_id>/reports_single',views.reports_single, name='reports_single'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sentiment_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('feedback_form.urls')),
]

templates/employees/addemployees.html
{% extends 'SideBar.html' %}
{% load static %}

{% block pagecss %}
<link rel="stylesheet" href="{% static 'css/employees/addemployee.css' %}">
{% endblock%}

{% block title %}
    Add Employees
{% endblock %}

{% block content %}
  <div class='add_employee_acc'>
    <h1>ADD EMPLOYEE</h1>
    <div class='form_container'>
            <form class='frm' action="{% url 'feedback:processaddemployee'%}" method="POST">
              {% csrf_token %}
                <input type="text" name="firstname" placeholder='First Name' required/>
                <input type="text" name="lastname" placeholder='Last Name' required/>
                <input type="text" name="position" placeholder='Position' required/>
                <input type="text" name="office" placeholder='Office' required/>
                {% if user.userclass.status == 1 %}
                <select name="acc_id" id='department' required>
                    <option value="">Please select an office</option>
                    {%for user in users %}
                    <option value="{{user.id}}">{{user.first_name}}</option>
                    {% endfor %}
                </select>
                {% else %}
                <select name="acc_id" id='department' required>
                  <option value="">Please select an office</option>
                  <option value="{{user.id}}">{{user.first_name}}</option>
                </select>
                {% endif %}
                <button type="submit" class='add'>Add</button>
                <a href="{% url 'feedback:employeelist'  %}"><button type="button" class="cancel">Cancel</button></a>
            </form>
    </div>
</div>



{% endblock %}

templates/employees/editemployees.html
{% extends 'SideBar.html' %}
{% load static %}

{% block pagecss %}
<link rel="stylesheet" href="{% static 'css/employees/editemployee.css' %}">
{% endblock%}

{% block title %}
    Edit Employee | {{employee.first_name}}
{% endblock %}


{% block content %}
  <div class='add_employee_acc'>
    <h1>Edit Employee: <strong>{{employee.first_name}} {{employee.last_name}}</strong> </h1>
    <div class='form_container'>
            <form class='frm' action="{% url 'feedback:process_edit_employee' employee.id %}" method="POST">
              {% csrf_token %}
                <input type="text" name="firstname" placeholder='First Name' value="{{employee.first_name}}"/>
                <input type="text" name="lastname" placeholder='Last Name' value="{{employee.last_name}}"/>
                <input type="text" name="position" placeholder='Position' value="{{employee.position}}" />
                <input type="text" name="office" placeholder='Office'value = "{{employee.office}}"/>
                {% if user.userclass.status == 1 %}
                <select name="acc_id" id='department' required>
                    <option value="">Please select an office</option>
                    {%for user in users %}
                    <option value="{{user.id}}">{{user.first_name}}</option>
                    {% endfor %}
                </select>
                {% else %}
                <select name="acc_id" id='department' required>
                  <option value="">Please select an office</option>
                  <option value="{{user.id}}">{{user.first_name}}</option>
                </select>
                {% endif %}
                <button type="submit" class='add'>Edit</button>
                <a href="{% url 'feedback:employeelist'  %}"><button type="button" class="cancel">Cancel</button></a>
            </form>
    </div>
</div>
{% endblock %}

templates/employees/employees.html
{% extends 'SideBar.html' %}
{% load static %}

{% block pagecss %}
<link rel="stylesheet" href="{% static 'css/employees/employeehome.css' %}">
{% endblock%}

{% block title %}
    Employees
{% endblock %}

{% block content %}
<div class='employees_page'>
    <h1 class="headtitle"> EMPLOYEES </h1>
    <div class='Search_bar'>
        <form action="{% url 'feedback:employeesearch' %}" method="GET" id="search-form">
            <input type="text" placeholder="Search Employee" name="search" id='search-input' />
            {% if user.userclass.status == 1%}
                <select name="category" id="search-category" class="filter">
                    <option value="">Office</option>
                    {%for user in users %}
                    <option value="{{user.id}}">{{user.first_name}}</option>
                    {% endfor %}
                </select>
            {% endif %}
            <select name="active" id="search-active" class="filter">
                <option value="">Status</option>
                <option value="True">Active</option>
                <option value="False">Inactive</option>
            </select>
        </form>
    </div>
    <div class="accounts_tbl" id="search-results">
        <table>
            <tr>
                <th>Department</th>
                <th>First name</th>
                <th>Last Name</th>
                <th>Position</th>
                <th>Office</th>
                <th>Status</th>
                <th colspan="2">Actions</th>
            </tr>
            {% for employee in employees %}
            <tr key={key}>
                <td>{{employee.office_user.first_name }}</td>
                <td>{{employee.first_name}}</td>
                <td>{{employee.last_name}}</td> 
                <td>{{employee.position}}</td>
                <td>{{employee.office}}</td>
                {% if employee.is_active %}
                        <td id="active">Active</td>
                    {% else %}
                        <td id="inactive">Inactive</td>
                    {% endif %}
                <td class="action-icons">
                    <a href="{% url 'feedback:edit_employee' employee.id %}">
                        <span id="edit" class="material-icons" title="edit">edit</span>
                    </a>
                    {% if employee.is_active %}
                    <a href="#" data-bs-toggle="modal" data-bs-target="#deactivateModal{{employee.id}}">
                        <span id="delete" class="material-icons">do_not_disturb_on</span>
                    </a>
                    {% else %}
                    <a href="#" data-bs-toggle="modal" data-bs-target="#activateModal{{employee.id}}">
                        <span id="activate" class="material-icons">check_circle</span>
                    </a>
                    {% endif %}
                </td>


            </tr>
             <!-- Delete Modal -->
             <div class="modal fade" id="deactivateModal{{ employee.id }}" tabindex="-1" role="dialog" aria-labelledby="deactivateModal{{ employee.id }}Label" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deactivateModal{{ employee.id }}Label">Confirmation</h5>
                        </div>
                        <div class="modal-body">
                            Are you sure you want to Deactivate this employee?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                            <a href="{% url 'feedback:deactivate_employee' employee.id %}">
                                <button type="button" class="btn btn-danger">Deactivate</button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="activateModal{{ employee.id }}" tabindex="-1" role="dialog" aria-labelledby="activateModal{{ employee.id }}Label" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="activateModal{{ employee.id }}Label">Confirmation</h5>
                        </div>
                        <div class="modal-body">
                            Are you sure you want to Activate this employee?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                            <a href="{% url 'feedback:activate_employee' employee.id %}">
                                <button type="button" class="btn btn-success">Activate</button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </table>
        <div class="pagebutton">
            <ul class="pagination">
                {% if employees.has_previous %}
                    <li class="page-item"><a href="?page=1" class="page-link">&laquo; First </a></li>
                    <li class="page-item"><a href="?page={{ employees.previous_page_number }}" class="page-link"> Previous </a></li>
                {% endif %}
    
                {% if employees.has_next %}
                    <li class="page-item "><a href="?page={{ employees.next_page_number }}" class="page-link"> Next </a></li>
                    <li class="page-item"><a href="?page={{ employees.paginator.num_pages }}" class="page-link">Last &raquo; </a></li>
    
                {% endif %}
            </ul> 
        </div> 
        <div class='Add_Office'>
            <a href="{% url 'feedback:addemployee'  %}"><button type="button" onClick="">ADD EMPLOYEE </button></a>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        var searchTimeout;

        $('#search-input, #search-category, #search-active').on('input', function() {
            clearTimeout(searchTimeout);
            searchTimeout = setTimeout(getSearchResults, 300); // Delay the search by 300 milliseconds
        });

        function getSearchResults() {
            var searchValue = $('#search-input').val();
            var categoryValue = $('#search-category').val();
            var activeValue = $('#search-active').val();
            $.ajax({
                url: $('#search-form').attr('action'),
                method: 'GET',
                data: { search: searchValue, category: categoryValue, active: activeValue },
                success: function(response) {
                    var searchResultsHTML = $(response).find('.accounts_tbl').html();
                    $('#search-results').html(searchResultsHTML);
                },
                error: function(xhr, textStatus, error) {
                    console.log(error);
                }
            });
        }
    });
</script>

{% endblock %}