feedback_form/urls.py
from django.urls import path
from django.conf import settings
from . import views
from django.conf.urls.static import static

app_name = 'feedback'
urlpatterns = [
    path('',views.index,name='index'),
        #Login
        path('loginview', views.loginview, name='loginview'),
        path('login/process', views.process, name='process'),
        path('logout', views.processlogout, name='processlogout'),

        #Account
        path('home', views.home, name='home'),
        path('adminhome',views.adminhome, name="adminhome"),
        path('accountsearch', views.accountsearch, name='accountsearch'),
        path('adminaddacc', views.adminAddAcc, name="adminaddacc"),
        path('adminaddacc/add_acc', views.add_acc, name="add_acc") ,
        # path('<int:user_id>/delete_acc/', views.delete_acc, name='delete_acc'),
        path('<int:user_id>/deactivate_acc/', views.deactivate_acc, name='deactivate_acc'),
        path('<int:user_id>/activate_acc/', views.activate_acc, name='activate_acc'),
        path('<int:user_id>/edit_acc/', views.edit_acc, name='edit_acc'),
        path('<int:user_id>/process_acc_edit/', views.process_acc_edit, name='process_acc_edit'),

        #User Settings
        path('usersettings', views.usersettings, name="usersettings"),
        path('editusersettings', views.editusersettings, name="editusersettings"),
        path('<int:user_id>/updateusersettings/',views.updateusersettings, name="updateusersettings"),

        #Employee
        path('employeelist', views.employeelist, name="employeelist"),
        path('employeesearch', views.employeesearch, name='employeesearch'),
        path('addemployee', views.addemployee, name='addemployee'),
        path('processaddemployee', views.processaddemployee, name='processaddemployee'),
        path('<int:employee_id>/deactivate_employee/',views.deactivate_employee,name="deactivate_employee"),
        path('<int:employee_id>/activate_employee/',views.activate_employee,name="activate_employee"),
        # path('<int:employee_id>/delete_employee/',views.delete_employee,name="delete_employee"),
        path('<int:employee_id>/edit_employee/',views.edit_employee,name="edit_employee"),
        path('<int:employee_id>/process_edit_employee/', views.process_edit_employee, name='process_edit_employee'),

        #Feedback
        path('generate_feedbackhome', views.generate_feedbackhome, name="generate_feedbackhome"),
        path('generate_client',views.generate_client,name="generate_client"),
        path('client_process', views.client_process, name="client_process"),
        path('client_feedback/<str:token>/<str:encrypt>/', views.client_feedback, name='client_feedback'),
        path('process_feedback',views.process_feedback, name="process_feedback"),
        path('thankyou', views.thankyou, name="thankyou"),

        #reports
        path('reportshome',views.reportshome, name='reportshome'),
        path('report_offices', views.report_offices, name='report_offices'),
        path('report_offices_search', views.report_offices_search, name='report_offices_search'),
        path('<int:user_id>/reports_feedbacks_search',views.reports_feedbacks_search,name='reports_feedbacks_search'),
        path('<int:user_id>/reports_officesummary',views.reports_officesummary,name='reports_officesummary'),
        path('<int:user_id>/reports_feedbacks',views.reports_feedbacks,name='reports_feedbacks'),
        path('<int:user_id>/reports_viewreports',views.reports_viewreports,name='reports_viewreports'),
        path('<int:user_id>/reports_viewreports_search',views.reports_viewreports_search,name='reports_viewreports_search'),
        path('<int:user_id>/reports_staff',views.reports_staff,name='reports_staff'),
        path('<int:user_id>/reports_staff_search',views.reports_staff_search,name='reports_staff_search'),
        path('<int:user_id>/<int:client_id>/reports_single',views.reports_single, name='reports_single'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sentiment_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('feedback_form.urls')),
]

templates/SideBar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/SideBar.css' %}">
    {% block pagecss %} {% endblock %}
    <title>{% block title %} {% endblock %}</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <div class="main-container">
        <a href="{% url 'feedback:home' %}"><img src="{% static 'image/login/cvsu-logo.png' %}" alt="cvsu-logo"></a>
        <div class="icons">
            {% if user.userclass.status == 1%}
            <a href="{% url 'feedback:adminhome' %}"><span class="material-icons icon-hover" title="Accounts">manage_accounts</span></a>
            {% endif %}
            <a href="{% url 'feedback:generate_feedbackhome' %}"><span id="Generate-Link" class="material-icons icon-hover" title="Generate Link">add_link </span></a>
            <a href="{% url 'feedback:employeelist' %}"><span class="material-icons icon-hover" title="Employee">badge</span></a>
            <a href="{% url 'feedback:reportshome' %}"><span id="Reports" class="material-icons icon-hover" title="Reports">analytics </span></a>
            <a href="{% url 'feedback:usersettings' %}"><span id="Settings" class="material-icons icon-hover" title="Settings">settings </span></a>
            <div class="dropdown dropdown-container">
                <span id="dropdownToggle" class="material-icons" title="Logout">arrow_drop_down</span>
                <div id="dropdownContent" class="dropdown-content">
                    <a href="{% url 'feedback:processlogout' %}" class="logout">Logout</a>
                </div>
            </div>
        </div>  
        <div class="content">
            <div class="header">
                <p>CVSU STAKEHOLDERS' FEEDBACK SYSTEM</p>
            </div>
            <div class="main-content">
                {% block content %} {% endblock %}
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function() {
            // Add a click event listener to the toggle
            $('#dropdownToggle').click(function() {
                // Toggle the visibility of the dropdown content
                $('#dropdownContent').toggle();
            });
        });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</body>
</html>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="./Accounts_home.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block pagecss %} {% endblock %}
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    {% block content %} {% endblock %}
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</html>

templates/basesidebar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block pagecss %} {% endblock %}
    <title>{% block title %} {% endblock %}</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
    <div class="container-fluid">
        <div class="row flex-nowrap ">
            <div class="bg-success col-auto col-md-1.5 min-vh-100 content-sidebar">
                <div class="bg-success p-2">
                    <ul class="nav nav-pills flex-column">
                        {% if user.userclass.status == 1%}
                        <li class="nav-item">
                            <a href="{% url 'feedback:adminhome' %}" class="nav-link text-white" aria-current="page">
                                <i class="fs-1 bi bi-newspaper"></i>
                            </a> 
                        </li>
                        {% endif %}
                        <li class="nav-item py-2 py-sm-0">
                            <a href="{% url 'feedback:employeelist' %}" class="nav-link text-white" aria-current="page">
                                <i class="fs-1 bi bi-people-fill"></i>
                            </a> 
                        </li>
                        <li class="nav-item py-2 py-sm-0">
                            <a href="{% url 'feedback:generate_feedbackhome' %}" class="nav-link text-white" aria-current="page">
                                <i class="fs-1 bi bi-card-list"></i>
                            </a> 
                        </li>
                        <li class="nav-item py-2 py-sm-0">
                            <a href="#" class="nav-link text-white" aria-current="page">
                                <i class="fs-1 bi bi-graph-up"></i>
                            </a> 
                        </li>
                        <li class="nav-item py-2 py-sm-0">
                            <a href="{% url 'feedback:usersettings' %}" class="nav-link text-white" aria-current="page">
                                <i class="fs-1 bi bi-person-fill-gear"></i>
                            </a> 
                        </li>
                    </ul>
                </div>
                <div class="dropdown open p-2">
                    <button class="btn border-none dropdown-toggle text-white" type="button" id="triggerId" data-bs-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false">
                                <i class="fs-2 bi bi-person-fill"></i>
                            </button>
                    <div class="dropdown-menu" aria-labelledby="triggerId">
                        <a href="{% url 'feedback:processlogout' %}" class="btn"><button class="dropdown-item">Logout</button></a>
                    </div>
                </div>
            </div>
            <!--content -->
            <div class="p-0 content-side">
                <img src="{% static 'image/login/cvsu-logo.png' %}" width="80px" class="logo">
                <h3 class="w-100 text-end border-bottom m-0 p-3 text-success">CvSU Stakeholders Feedback System</h3>
                <div class="p-4">
                    {% block content %} {% endblock %}
                </div>
            </div>
        </div>
    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</html>

templates/feedbackbase.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    {% block pagecss %} {% endblock %}
    <title>{% block title %} {% endblock %}</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
        <img src="{% static 'image/login/cvsu-logo.png' %}" width="120px" class="logo">
        <h3 class="text-end border-bottom m-0 p-4 backgroundcvsu">CVSU STAKEHOLDERS' FEEDBACK SYSTEM</h3>
        <div class="p-4">
            {% block content %} {% endblock %}
        </div>
</body>              
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</html>

templates/home.html
{% extends 'feedbackbase.html' %}
{% load static %}

{% block pagecss %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock%}

{% block title %}
    {{user.username}} | Home
{% endblock %}

{% block content %}
<div class="Main">
    <header></header>
    {% if error_message %}
        <p class="alert alert-danger text-center">
            <strong>{{error_message}}</strong>
        </p>
    {% endif %}
    <!-- Icons -->
        <div class="icons">
            {% if user.userclass.status == 1%}
            <a href="{% url 'feedback:adminhome' %}"><span class="material-icons icon-hover" title="Accounts"><span class="material-title">Accounts</span>manage_accounts</span></a>
            {% endif %}
            <a href="{% url 'feedback:generate_feedbackhome' %}"><span id="Generate-Link" class="material-icons" title="Generate Link"><span class="material-title">Generate Link</span> add_link </span></a>
            <a href="{% url 'feedback:employeelist' %}"><span id="Employees" class="material-icons" title="Employee"><span class="material-title">Employee</span> badge</span></a>
            <a href="{% url 'feedback:reportshome' %}"><span id="Reports" class="material-icons" title="Reports"><span class="material-title">Reports</span> analytics </span></a>
            <a href="{% url 'feedback:usersettings' %}"><span id="Settings" class="material-icons" title="settings"><span class="material-title">Settings</span> settings </span></a>
        </div>  
</div>
{% endblock %}