feedback_form/urls.py
from django.urls import path
from django.conf import settings
from . import views
from django.conf.urls.static import static

app_name = 'feedback'
urlpatterns = [
    path('',views.index,name='index'),
        #Login
        path('loginview', views.loginview, name='loginview'),
        path('login/process', views.process, name='process'),
        path('logout', views.processlogout, name='processlogout'),

        #Account
        path('home', views.home, name='home'),
        path('adminhome',views.adminhome, name="adminhome"),
        path('accountsearch', views.accountsearch, name='accountsearch'),
        path('adminaddacc', views.adminAddAcc, name="adminaddacc"),
        path('adminaddacc/add_acc', views.add_acc, name="add_acc") ,
        # path('<int:user_id>/delete_acc/', views.delete_acc, name='delete_acc'),
        path('<int:user_id>/deactivate_acc/', views.deactivate_acc, name='deactivate_acc'),
        path('<int:user_id>/activate_acc/', views.activate_acc, name='activate_acc'),
        path('<int:user_id>/edit_acc/', views.edit_acc, name='edit_acc'),
        path('<int:user_id>/process_acc_edit/', views.process_acc_edit, name='process_acc_edit'),

        #User Settings
        path('usersettings', views.usersettings, name="usersettings"),
        path('editusersettings', views.editusersettings, name="editusersettings"),
        path('<int:user_id>/updateusersettings/',views.updateusersettings, name="updateusersettings"),

        #Employee
        path('employeelist', views.employeelist, name="employeelist"),
        path('employeesearch', views.employeesearch, name='employeesearch'),
        path('addemployee', views.addemployee, name='addemployee'),
        path('processaddemployee', views.processaddemployee, name='processaddemployee'),
        path('<int:employee_id>/deactivate_employee/',views.deactivate_employee,name="deactivate_employee"),
        path('<int:employee_id>/activate_employee/',views.activate_employee,name="activate_employee"),
        # path('<int:employee_id>/delete_employee/',views.delete_employee,name="delete_employee"),
        path('<int:employee_id>/edit_employee/',views.edit_employee,name="edit_employee"),
        path('<int:employee_id>/process_edit_employee/', views.process_edit_employee, name='process_edit_employee'),

        #Feedback
        path('generate_feedbackhome', views.generate_feedbackhome, name="generate_feedbackhome"),
        path('generate_client',views.generate_client,name="generate_client"),
        path('client_process', views.client_process, name="client_process"),
        path('client_feedback/<str:token>/<str:encrypt>/', views.client_feedback, name='client_feedback'),
        path('process_feedback',views.process_feedback, name="process_feedback"),
        path('thankyou', views.thankyou, name="thankyou"),

        #reports
        path('reportshome',views.reportshome, name='reportshome'),
        path('report_offices', views.report_offices, name='report_offices'),
        path('report_offices_search', views.report_offices_search, name='report_offices_search'),
        path('<int:user_id>/reports_feedbacks_search',views.reports_feedbacks_search,name='reports_feedbacks_search'),
        path('<int:user_id>/reports_officesummary',views.reports_officesummary,name='reports_officesummary'),
        path('<int:user_id>/reports_feedbacks',views.reports_feedbacks,name='reports_feedbacks'),
        path('<int:user_id>/reports_viewreports',views.reports_viewreports,name='reports_viewreports'),
        path('<int:user_id>/reports_viewreports_search',views.reports_viewreports_search,name='reports_viewreports_search'),
        path('<int:user_id>/reports_staff',views.reports_staff,name='reports_staff'),
        path('<int:user_id>/reports_staff_search',views.reports_staff_search,name='reports_staff_search'),
        path('<int:user_id>/<int:client_id>/reports_single',views.reports_single, name='reports_single'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sentiment_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('feedback_form.urls')),
]

templates/feedback/Client-Form.html
{% extends 'feedbackbase.html' %}
{% load static %}

{% block pagecss %}
<link rel="stylesheet" href="{% static 'css/feedback/clientforms.css' %}">
{% endblock%}

{% block title %}
    Feedback | Client-form
{% endblock %}

{% block content %}
<div class="Main">
    <!-- <Header /> -->
    <div class="Container">
        <form id="feedbackForm" method="POST" action="{% url 'feedback:client_process' %}">
            {% csrf_token %}
            <label for="name">
                Name <input type="text" id="name" name="name" required/>
            </label>
            <label for="gency">
                Agency <input type="text" id="gency" name="gency" />
            </label>
            <label for="email">
                Email Address <input type="email" id="email" name="email" required/>
            </label>
            <label for="staff">
                Attending Staff<br> <select name="staff" required>
                    <option value="">Please select an attending staff</option>
                    {% for employee in employees %}
                        <option value="{{ employee.id }}">{{ employee.first_name }} {{ employee.last_name }}</option>
                    {% endfor %}
                </select>
            </label>
            <br>
            <label for="pov">Purpose of visit</label>
            <textarea id="pov" name="pov"></textarea>
            <!-- <p>By proceeding you agreed to our <span>Terms & Agreements.</span></p> -->
            <button type="button" id="proceedBtn" class="proceed">Proceed</button>
            <a href="{% url 'feedback:generate_feedbackhome' %}">
                <button type="button" class="cancel">Cancel</button>
            </a>
        </form>
    </div>
</div>

<div class="modal fade" id="getlink" tabindex="-1" role="dialog" aria-labelledby="getlinkLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="getlinkLabel">Confirmation</h5>
            </div>
            <div class="modal-body">
                Do you wish to proceed in creating a Link?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
                <button type="button" id="proceedModalBtn" class="btn btn-success">Proceed</button>
            </div>
        </div>
    </div>
</div>

<script>
    document.getElementById("proceedBtn").addEventListener("click", function() {
        $('#getlink').modal('show');
    });

    document.getElementById("proceedModalBtn").addEventListener("click", function() {
        document.getElementById("feedbackForm").submit();
    });
</script>
{% endblock %}

templates/feedback/client_feedback.html
{% extends 'feedbackbase.html' %}
{% load static %}

{% block pagecss %}
<link rel="stylesheet" href="{% static 'css/feedback/feedback-form.css' %}">
{% endblock%}

{% block title %}
    Feedback | Feedback Form
{% endblock %}

{% block content %}

            <div class="main">
            <!-- <Header /> -->
            <div class="Container">
                <!-- <img src="./images/cvsu-logo.png" alt="cvsu-logo" />
                <p>Republic of the Philippines</p>
                <p id="Cvsu">Cavite State University</p>
                <p>Don Severino delas Alas Campus</p>
                <p>Indang, Cavite</p>  -->
                <p id="SFF">STAKEHOLDERS' FEEDBACK FORM</p>
                <form method="POST" action="{% url 'feedback:process_feedback' %}">
                    {% csrf_token %}
                    <table>
                        <tr>
                            <th>Area of Concern</th>
                            <td>Highly Satisfied</td>
                            <td>Very Satisfied</td>
                            <td>Moderately Satisfied</td>
                            <td>Barely Satisfied</td>
                            <td>Not Satisfied</td>
                        </tr>
                        <tr>
                            <th></th>
                            <td>5</td>
                            <td>4</td>
                            <td>3</td>
                            <td>2</td>
                            <td>1</td>
                        </tr>
                        <tr>
                            <th>A . Courtesy</th>
                            <td><input type="radio" name='courtesy' value='5' placeholder="0" required></input></td>
                            <td><input type="radio" name='courtesy' value='4' placeholder="0"></input></td>
                            <td><input type="radio" name='courtesy' value='3' placeholder="0"></input></td>
                            <td><input type="radio" name='courtesy' value='2' placeholder="0"></input></td>
                            <td><input type="radio" name='courtesy' value='1' placeholder="0"></input></td>
                        </tr>
                        <tr>
                            <th>B . Services</th>
                        </tr>
                        <tr>
                            <th id="satisfactory">1 . Quality</th>
                            <td><input type="radio" name='quality' value="5" placeholder="0" required></input></td>
                            <td><input type="radio" name='quality' value="4" placeholder="0"></input></td>
                            <td><input type="radio" name='quality' value="3" placeholder="0"></input></td>
                            <td><input type="radio" name='quality' value="2" placeholder="0"></input></td>
                            <td><input type="radio" name='quality' value="1" placeholder="0"></input></td>
                        </tr>
                        <tr>
                            <th id="satisfactory">2 . Timeliness</th>
                            <td><input type="radio" name='timeliness' value="5" placeholder="0" required></input></td>
                            <td><input type="radio" name='timeliness' value="4" placeholder="0"></input></td>
                            <td><input type="radio" name='timeliness' value="3" placeholder="0"></input></td>
                            <td><input type="radio" name='timeliness' value="2" placeholder="0"></input></td>
                            <td><input type="radio" name='timeliness' value="1" placeholder="0"></input></td>
                        </tr>
                        <tr>
                            <th id="satisfactory">3 . Efficiency</th>
                            <td><input type="radio" name="efficiency" value='5' placeholder="0" required></input></td>
                            <td><input type="radio" name="efficiency" value='4' placeholder="0"></input></td>
                            <td><input type="radio" name="efficiency" value='3' placeholder="0"></input></td>
                            <td><input type="radio" name="efficiency" value='2' placeholder="0"></input></td>
                            <td><input type="radio" name="efficiency" value='1' placeholder="0"></input></td>
                        </tr>
                        <tr>
                            <th>C .  Physical Condition of workspace</th>
                        </tr>
                        <tr>
                            <th id="satisfactory">1 . Cleanliness</th>
                            <td><input type="radio" name='cleanliness' value='5'placeholder="0" required></input></td>
                            <td><input type="radio" name='cleanliness' value='4'placeholder="0"></input></td>
                            <td><input type="radio" name='cleanliness' value='3'placeholder="0"></input></td>
                            <td><input type="radio" name='cleanliness' value='2'placeholder="0"></input></td>
                            <td><input type="radio" name='cleanliness' value='1'placeholder="0"></input></td>
                        </tr>
                        <tr>
                            <th id="satisfactory">2 . Comfort</th>
                            <td><input type="radio" name='comfort' value='5' placeholder="0" required></input></td>
                            <td><input type="radio" name='comfort' value='4' placeholder="0"></input></td>
                            <td><input type="radio" name='comfort' value='3' placeholder="0"></input></td>
                            <td><input type="radio" name='comfort' value='2' placeholder="0"></input></td>
                            <td><input type="radio" name='comfort' value='1' placeholder="0"></input></td>
                        </tr>
                        <tr></tr>
                    </table>
                    <label>Comments and Suggestion:</label>
                    <textarea id="" name="comments" placeholder="Input comments and suggestion" required></textarea>
                    <input type="hidden" name="client_id" value="{{client.id}}" />
                    <button type="submit">Proceed</button>
                </form>
            </div>
        </div>
        <script>
            // Refresh the page once after it opens
            if (performance.navigation.type !== 1) {
                // Perform the refresh only if it's not a navigation reload
                window.onload = function () {
                    window.location.reload();
                };
            }
        </script>
{% endblock %}

templates/feedback/generate_link.html
{% extends 'SideBar.html' %}
{% load static %}

{% block pagecss %}
<link rel="stylesheet" href="{% static 'css/feedback/generate_link.css' %}">
{% endblock%}

{% block title %}
    Employees
{% endblock %}

{% block content %}
<h1>GENERATE LINK</h1>
<form action="{% url 'feedback:generate_client' %}" method="POST">
    {% csrf_token %}
    <button type="submit">Click to Create a Form</button>
</form>

{% endblock %}

templates/feedback/thankyou.html
{% extends 'SideBar.html' %}
{% load static %}

{% block pagecss %}
<link rel="stylesheet" href="{% static 'css/feedback/thank_you.css' %}">
{% endblock%}

{% block title %}
    Thankyou!
{% endblock %}

{% block content %}
<div class="head">
    <!-- <Header /> --> 
    <div class="Container">
        <h2>THANK YOU!</h2>
        <a href="{% url 'feedback:home' %}" class="home btn">Home</a>
    </div>
    <!-- <Footer /> -->
</div>
{% endblock %}

templates/feedback/token_link.html
{% extends 'feedbackbase.html' %}

{% load tz %}

{% load static %}

{% block pagecss %}
<link rel="stylesheet" href="{% static 'css/feedback/tokenlinks.css' %}">
{% endblock%}

{% block title %}
    Feedback | Client-form
{% endblock %}

{% block content %}

<div class="Main">
    <div class="Container">
        <form method="POST" action="{% url 'feedback:client_process' %}">
            {% csrf_token %}
            <label for="name">
                Name <input type="text" id="name" name="name" value="{{client.client_name}}" required/>
            </label>
            <label for="gency">
                Agency <input type="text" id="gency" name="gency" value="{{client.client_agency}}" />
            </label>
            <label for="email">
                Email Address <input type="email" id="email" name="email" value="{{client.client_email}}" required/>
            </label>
            <label for="attending-staff">
                Attending Staff <input type="text" id="email" name="email" value="{{staff.first_name}} {{staff.last_name}}" required/>
            </label>
            </label>
            <p>Click the link below to provide feedback:</p>
            <p>The link will expire at: {{ expiration_time|timezone:"Asia/Manila" }}</p>
            <a href="{{ link }}"><button type="button">{{ link }}</button></a>
        </form>
</div>
{% endblock %}